using System;
using System.Drawing;
using System.IO;
using System.Web;
using ThoughtWorks.QRCode.Codec;
using ThoughtWorks.QRCode.Codec.Data;

namespace CreateQrCodeAndMergeImage
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("请输入要生成物料的数量！！！");
            var readCount = Console.ReadLine();
            var result = CommonHelper.IsNumeric(readCount);
            if (!result)
            {
                Console.WriteLine("请输入正确数量");
            }
            else
            {
                var createNum = Convert.ToInt32(readCount);
                const string qrEncodingType = "BYTE";
                const string createLevel = "H";
                const int version = 8;
                const int scale = 12;

                var showurlArr = GetShortUrl();
                for (int i = 0; i < createNum; i++)
                {
                    var jumpAddress = showurlArr[i];

                    //1.生成二维码图片
                    var qrCodeFilePath = CreateCode_Choose(jumpAddress, qrEncodingType, createLevel, version, scale);

                    //2.拼接二维码图片，生成物料图片
                    var waterMark = WaterMarkImage(qrCodeFilePath);
                    DIVWaterMark(waterMark, i);
                    Console.WriteLine("第{0}合成图片成功!", i + 1);
                }
            }

            Console.ReadLine();
        }

        //生成二维码方法（简单）
        private static void CreateCode_Simple(string nr)
        {
            var qrCodeEncoder = new QRCodeEncoder
            {
                QRCodeEncodeMode = QRCodeEncoder.ENCODE_MODE.BYTE,
                QRCodeScale = 4,
                QRCodeVersion = 8,
                QRCodeErrorCorrect = QRCodeEncoder.ERROR_CORRECTION.M
            };
            //System.Drawing.Image image = qrCodeEncoder.Encode("15377541070 上海 Akon_Coder");
            Image image = qrCodeEncoder.Encode(nr);
            var filename = DateTime.Now.ToString("yyyymmddhhmmssfff") + ".jpg";
            var filepath = System.Web.HttpContext.Current.Server.MapPath(@"~\Upload") + "\\" + filename;
            var fs = new FileStream(filepath, FileMode.OpenOrCreate, FileAccess.Write);
            image.Save(fs, System.Drawing.Imaging.ImageFormat.Jpeg);

            fs.Close();
            image.Dispose();
            //二维码解码
            var codeDecoder = CodeDecoder(filepath);
        }

        /// <summary>
        /// 生成二维码方法（复杂）
        /// </summary>
        /// <param name="strData">要生成的文字或者数字，支持中文。如： "15377541070 上海 Akon_Coder</param>
        /// <param name="qrEncoding">三种尺寸：BYTE ，ALPHA_NUMERIC，NUMERIC</param>
        /// <param name="level">大小：L M Q H</param>
        /// <param name="version">版本：如 8</param>
        /// <param name="scale">比例：如 4</param>
        /// <returns></returns>
        public static string CreateCode_Choose(string strData, string qrEncoding, string level, int version, int scale)
        {
            var qrCodeEncoder = new QRCodeEncoder();
            string encoding = qrEncoding;
            switch (encoding)
            {
                case "Byte":
                    qrCodeEncoder.QRCodeEncodeMode = QRCodeEncoder.ENCODE_MODE.BYTE;
                    break;
                case "AlphaNumeric":
                    qrCodeEncoder.QRCodeEncodeMode = QRCodeEncoder.ENCODE_MODE.ALPHA_NUMERIC;
                    break;
                case "Numeric":
                    qrCodeEncoder.QRCodeEncodeMode = QRCodeEncoder.ENCODE_MODE.NUMERIC;
                    break;
                default:
                    qrCodeEncoder.QRCodeEncodeMode = QRCodeEncoder.ENCODE_MODE.BYTE;
                    break;
            }

            qrCodeEncoder.QRCodeScale = scale;
            qrCodeEncoder.QRCodeVersion = version;
            switch (level)
            {
                case "L":
                    qrCodeEncoder.QRCodeErrorCorrect = QRCodeEncoder.ERROR_CORRECTION.L;
                    break;
                case "M":
                    qrCodeEncoder.QRCodeErrorCorrect = QRCodeEncoder.ERROR_CORRECTION.M;
                    break;
                case "Q":
                    qrCodeEncoder.QRCodeErrorCorrect = QRCodeEncoder.ERROR_CORRECTION.Q;
                    break;
                default:
                    qrCodeEncoder.QRCodeErrorCorrect = QRCodeEncoder.ERROR_CORRECTION.H;
                    break;
            }
            //文字生成图片
            Image image = qrCodeEncoder.Encode(strData);
            var filename = DateTime.Now.ToString("yyyymmddhhmmssfff") + ".jpg";
            var filepath = AppDomain.CurrentDomain.BaseDirectory + @"\UploadPic\" + filename;
            var fs = new FileStream(filepath, FileMode.OpenOrCreate, FileAccess.Write);
            image.Save(fs, System.Drawing.Imaging.ImageFormat.Jpeg);
            fs.Close();
            image.Dispose();
            return filepath;
        }

        /// <summary>
        /// 二维码解码
        /// </summary>
        /// <param name="filePath">图片路径</param>
        /// <returns></returns>
        public static string CodeDecoder(string filePath)
        {
            if (!File.Exists(filePath))
                return null;
            var myBitmap = new Bitmap(Image.FromFile(filePath));
            var decoder = new QRCodeDecoder();
            var decodedString = decoder.decode(new QRCodeBitmapImage(myBitmap));
            return decodedString;
        }

        /// <summary>
        /// 生成新的二维码
        /// </summary>
        /// <returns></returns>
        public static bool CreateImg()
        {
            Image img1 = Image.FromFile(@"D:\Pictures\hwl.jpg");
            Image img2 = Image.FromFile(@"D:\Pictures\sgh.jpg");
            Image img3 = Image.FromFile(@"D:\Pictures\syf.jpg");
            Image img = ImageMergeHelper.ImgMerge(200, 300, 5, null,
                new Image[] {img1, img2, img3, img2, img3, img2});
            img.Save(@"D:\Pictures\allinone.jpg", System.Drawing.Imaging.ImageFormat.Jpeg);
            return true;
        }

        #region 水印预设

        /// <summary>
        /// 水印文字预设
        /// </summary>
        /// <returns></returns>
        private static WaterMark WaterMarkFont()
        {
            var waterMark = new WaterMark
            {
                WaterMarkType = WaterMarkTypeEnum.Text,
                Transparency = 0.7f,
                Text = "dunitian.cnblogs.com",
                FontStyle = System.Drawing.FontStyle.Bold,
                FontFamily = "Consolas",
                FontSize = 20f,
                BrushesColor = System.Drawing.Brushes.Black,
                WaterMarkLocation = WaterMarkLocationEnum.CenterCenter
            };
            return waterMark;
        }

        /// <summary>
        /// 图片水印预设
        /// </summary>
        /// <returns></returns>
        private static WaterMark WaterMarkImage(string filePath)
        {
            var waterMark = new WaterMark
            {
                WaterMarkType = WaterMarkTypeEnum.Image,
                ImgPath = filePath,
                WaterMarkLocation = WaterMarkLocationEnum.CenterCenter,
                Transparency = 1f
            };
            return waterMark;
        }

        #endregion

        #region 水印操作

        /// <summary>
        /// 单个水印操作
        /// </summary>
        /// <param name="waterMark"></param>
        /// <param name="index"></param>
        private static void DIVWaterMark(WaterMark waterMark, int index = 0)
        {
            #region 必须参数获取

            //图片路径
            var filePath = AppDomain.CurrentDomain.BaseDirectory + @"\Pictures\background.jpg";
            //文件名
            string fileName = Path.GetFileNameWithoutExtension(filePath);
            //图片所处目录
            string dirPath = Path.GetDirectoryName(filePath);
            //存放目录     
            string savePath = dirPath + "\\ProductWaterMark";
            //是否存在，不存在就创建
            if (!Directory.Exists(savePath))
            {
                Directory.CreateDirectory(savePath);
            }

            #endregion

            #region 水印操作

            Image successImage = WaterMarkHelper.SetWaterMark(filePath, waterMark);
            if (successImage != null)
            {
                //保存图片（不管打不打开都保存）
                successImage.Save(savePath + "\\" + index + ".png", System.Drawing.Imaging.ImageFormat.Png);
            }
            else
            {
                Console.WriteLine("水印失败！请检查原图和水印图！");
            }

            #endregion
        }

        #endregion


        public static string[] GetShortUrl()
        {

            return new[]
            {
                "http://i2oo.cn/p7zHM",
                "http://i2oo.cn/sxyZ6",
                "http://i2oo.cn/nSxis",
                "http://i2oo.cn/avx3P",
                "http://i2oo.cn/3QAQj",
                "http://i2oo.cn/9tv6n",
                "http://i2oo.cn/B4uyR",
                "http://i2oo.cn/UiuEm",
                "http://i2oo.cn/NLtYf",
                "http://i2oo.cn/EF1FT",
                "http://i2oo.cn/HJ1ao",
                "http://i2oo.cn/J8iP9",
                "http://i2oo.cn/LGqCV",
                "http://i2oo.cn/MkFAq",
                "http://i2oo.cn/PNFNB",
                "http://i2oo.cn/Q5oWX",
                "http://i2oo.cn/SU881",
                "http://i2oo.cn/Tg8nD",
                "http://i2oo.cn/VwmMZ",
                "http://i2oo.cn/Wekdu",
                "http://i2oo.cn/Y3jvE",
                "http://i2oo.cn/ZcjUb",
                "http://i2oo.cn/ba57A",
                "http://i2oo.cn/c26mH",
                "http://i2oo.cn/eh6sd",
                "http://i2oo.cn/CYgKy",
                "http://i2oo.cn/6pCcK",
                "http://i2oo.cn/5WetC",
                "http://i2oo.cn/jzeBr",
                "http://i2oo.cn/m7dTM",
                "http://i2oo.cn/8xcj6",
                "http://i2oo.cn/FScps",
                "http://i2oo.cn/qvbJP",
                "http://i2oo.cn/1Q22j",
                "http://i2oo.cn/ttZ1n",
                "http://i2oo.cn/v4Z9R",
                "http://i2oo.cn/AiYRm",
                "http://i2oo.cn/yLX5f",
                "http://i2oo.cn/zFWzT",
                "http://i2oo.cn/ppJWG",
                "http://i2oo.cn/ps8VZ",
                "http://i2oo.cn/pnG7q",
                "http://i2oo.cn/pak7f",
                "http://i2oo.cn/p3NTQ",
                "http://i2oo.cn/p95Sg",
                "http://i2oo.cn/pBURx",
                "http://i2oo.cn/pUgRE",
                "http://i2oo.cn/pNwQX",
                "http://i2oo.cn/pEePo",
                "http://i2oo.cn/pH3Pa",
                "http://i2oo.cn/pJc44",
                "http://i2oo.cn/pLaMe",
                "http://i2oo.cn/pM2LA",
                "http://i2oo.cn/pPhLD",
                "http://i2oo.cn/pQYKV",
                "http://i2oo.cn/pSpJ8",
                "http://i2oo.cn/pTWJh",
                "http://i2oo.cn/p7zHM",
                "http://i2oo.cn/pW7Gd",
                "http://i2oo.cn/pXxEu",
                "http://i2oo.cn/pZSEU",
                "http://i2oo.cn/p2vN7",
                "http://i2oo.cn/pcQDk",
                "http://i2oo.cn/pdtDs",
                "http://i2oo.cn/pC4UK",
                "http://i2oo.cn/pgiBb",
                "http://i2oo.cn/p5Lwt",
                "http://i2oo.cn/pjFww",
                "http://i2oo.cn/pmJ9S",
                "http://i2oo.cn/p883j",
                "http://i2oo.cn/pFG3r",
                "http://i2oo.cn/pqkfH",
                "http://i2oo.cn/p1Na2",
                "http://i2oo.cn/pt5ni",
                "http://i2oo.cn/pvUn3",
                "http://i2oo.cn/pAghR",
                "http://i2oo.cn/pyws6",
                "http://i2oo.cn/pzepy",
                "http://i2oo.cn/sp3pG",
                "http://i2oo.cn/sscrY",
                "http://i2oo.cn/snnzF",
                "http://i2oo.cn/saZzf",
                "http://i2oo.cn/s3syP",
                "http://i2oo.cn/s9XxC",
                "http://i2oo.cn/sBrAx",
                "http://i2oo.cn/sUVAN",
                "http://i2oo.cn/sDyvX",
                "http://i2oo.cn/sETuo",
                "http://i2oo.cn/sGAun",
                "http://i2oo.cn/sJRt4",
                "http://i2oo.cn/sKu1e",
                "http://i2oo.cn/sMPiv",
                "http://i2oo.cn/s41iD",
                "http://i2oo.cn/sQMqV",
                "http://i2oo.cn/sRqFm",
                "http://i2oo.cn/sTKFh",
                "http://i2oo.cn/s7ooL",
                "http://i2oo.cn/sWH8c",
                "http://i2oo.cn/sXmmu",
                "http://i2oo.cn/sZEmB",
                "http://i2oo.cn/s2jkT",
                "http://i2oo.cn/scDjk",
                "http://i2oo.cn/sd6jp",
                "http://i2oo.cn/sCB5J",
                "http://i2oo.cn/sgC6b",
                "http://i2oo.cn/s59g1",
                "http://i2oo.cn/sjdg9",
                "http://i2oo.cn/smfCS",
                "http://i2oo.cn/s8be5",
                "http://i2oo.cn/sFndz",
                "http://i2oo.cn/sqZdH",
                "http://i2oo.cn/s1scZ",
                "http://i2oo.cn/stXbq",
                "http://i2oo.cn/svrb3",
                "http://i2oo.cn/sAV2Q",
                "http://i2oo.cn/sxyZ6",
                "http://i2oo.cn/szTYy",
                "http://i2oo.cn/hrAYE",
                "http://i2oo.cn/hsRXY",
                "http://i2oo.cn/hhuWF",
                "http://i2oo.cn/haPWa",
                "http://i2oo.cn/hf1VP",
                "http://i2oo.cn/h9M7C",
                "http://i2oo.cn/hwqTA",
                "http://i2oo.cn/hUKTN",
                "http://i2oo.cn/hDoSW",
                "http://i2oo.cn/hEHR8",
                "http://i2oo.cn/hGmRn",
                "http://i2oo.cn/hJEQM",
                "http://i2oo.cn/hKjPd",
                "http://i2oo.cn/hMD4v",
                "http://i2oo.cn/h464U",
                "http://i2oo.cn/hQBM7",
                "http://i2oo.cn/hRCLm",
                "http://i2oo.cn/hT9Ls",
                "http://i2oo.cn/h7dKK",
                "http://i2oo.cn/hWfJc",
                "http://i2oo.cn/hXbHt",
                "http://i2oo.cn/hZnHw",
                "http://i2oo.cn/h2ZGT",
                "http://i2oo.cn/hcsEj",
                "http://i2oo.cn/hdXEr",
                "http://i2oo.cn/hCrNJ",
                "http://i2oo.cn/hgVD2",
                "http://i2oo.cn/h6yU1",
                "http://i2oo.cn/hjTU9",
                "http://i2oo.cn/hkABR",
                "http://i2oo.cn/h8Rw5",
                "http://i2oo.cn/hou9z",
                "http://i2oo.cn/hqP9G",
                "http://i2oo.cn/hi13Z",
                "http://i2oo.cn/htMfq",
                "http://i2oo.cn/huqff",
                "http://i2oo.cn/hAKaQ",
                "http://i2oo.cn/hxong",
                "http://i2oo.cn/hzHhx",
                "http://i2oo.cn/nrmhE",
                "http://i2oo.cn/nsEsX",
                "http://i2oo.cn/nhjpo",
                "http://i2oo.cn/naDpa",
                "http://i2oo.cn/nf6r4",
                "http://i2oo.cn/n9wze",
                "http://i2oo.cn/nweyA",
                "http://i2oo.cn/nU3yD",
                "http://i2oo.cn/nDcxV",
                "http://i2oo.cn/nEaA8",
                "http://i2oo.cn/nG2Ah",
                "http://i2oo.cn/nJhvL",
                "http://i2oo.cn/nKYud",
                "http://i2oo.cn/nMptu",
                "http://i2oo.cn/n4WtB",
                "http://i2oo.cn/nPz17",
                "http://i2oo.cn/nR7ik",
                "http://i2oo.cn/nSxis",
                "http://i2oo.cn/n7SqK",
                "http://i2oo.cn/nVvFb",
                "http://i2oo.cn/nXQot",
                "http://i2oo.cn/nYtow",
                "http://i2oo.cn/n248S",
                "http://i2oo.cn/nbimj",
                "http://i2oo.cn/ndLmr",
                "http://i2oo.cn/neFkH",
                "http://i2oo.cn/ngJj2",
                "http://i2oo.cn/n685i",
                "http://i2oo.cn/njG53",
                "http://i2oo.cn/nkk6R",
                "http://i2oo.cn/n8Ng6",
                "http://i2oo.cn/no5Cy",
                "http://i2oo.cn/nqUCG",
                "http://i2oo.cn/nigeY",
                "http://i2oo.cn/ntwdF",
                "http://i2oo.cn/nuedf",
                "http://i2oo.cn/nA3cP",
                "http://i2oo.cn/nxcbC",
                "http://i2oo.cn/nza2x",
                "http://i2oo.cn/ar22N",
                "http://i2oo.cn/ashZW",
                "http://i2oo.cn/ahYYo",
                "http://i2oo.cn/aapYn",
                "http://i2oo.cn/afWXM",
                "http://i2oo.cn/a3zWe",
                "http://i2oo.cn/aw7Vv",
                "http://i2oo.cn/aBxVD",
                "http://i2oo.cn/aDS7V",
                "http://i2oo.cn/aNvTm",
                "http://i2oo.cn/aGQTh",
                "http://i2oo.cn/aHtSL",
                "http://i2oo.cn/aK4Rc",
                "http://i2oo.cn/aLiQu",
                "http://i2oo.cn/a4LQB",
                "http://i2oo.cn/aPFPT",
                "http://i2oo.cn/aRJ4k",
                "http://i2oo.cn/aS84p",
                "http://i2oo.cn/a7GMJ",
                "http://i2oo.cn/aVkLb",
                "http://i2oo.cn/aXNK1",
                "http://i2oo.cn/aY5K9",
                "http://i2oo.cn/a2UJS",
                "http://i2oo.cn/abgH5",
                "http://i2oo.cn/adwGz",
                "http://i2oo.cn/aeeGH",
                "http://i2oo.cn/ag3EZ",
                "http://i2oo.cn/a6cNq",
                "http://i2oo.cn/ajaN3",
                "http://i2oo.cn/ak2DQ",
                "http://i2oo.cn/a8hUg",
                "http://i2oo.cn/aoYBy",
                "http://i2oo.cn/aqpBE",
                "http://i2oo.cn/aiWwX",
                "http://i2oo.cn/a1z9F",
                "http://i2oo.cn/au79a",
                "http://i2oo.cn/avx3P",
                "http://i2oo.cn/axSfC",
                "http://i2oo.cn/ayvaA",
                "http://i2oo.cn/frQaN",
                "http://i2oo.cn/fptnW",
                "http://i2oo.cn/fh4h8",
                "http://i2oo.cn/fnihn",
                "http://i2oo.cn/ffLsM",
                "http://i2oo.cn/f3Fpd",
                "http://i2oo.cn/fwJrv",
                "http://i2oo.cn/fB8rU",
                "http://i2oo.cn/fDEz7",
                "http://i2oo.cn/fNjym",
                "http://i2oo.cn/fGDys",
                "http://i2oo.cn/fH6xK",
                "http://i2oo.cn/fKBAc",
                "http://i2oo.cn/fLCvt",
                "http://i2oo.cn/f49vw",
                "http://i2oo.cn/fPduT",
                "http://i2oo.cn/fRftj",
                "http://i2oo.cn/fSbtr",
                "http://i2oo.cn/f7n1J",
                "http://i2oo.cn/fVZi2",
                "http://i2oo.cn/fXsqi",
                "http://i2oo.cn/rL7A ",
                "http://i2oo.cn/pVKmH",
                "http://i2oo.cn/syKsd",
                "http://i2oo.cn/nTJKy",
                "http://i2oo.cn/aAHcK",
                "http://i2oo.cn/3RGtC",
                "http://i2oo.cn/9uGBr",
                "http://i2oo.cn/BPETM",
                "http://i2oo.cn/U1Nj6",
                "http://i2oo.cn/NMNps",
                "http://i2oo.cn/EqDJP",
                "http://i2oo.cn/HKU2j",
                "http://i2oo.cn/JoB1n",
                "http://i2oo.cn/LHB9R",
                "http://i2oo.cn/MmwRm",
                "http://i2oo.cn/PE95f",
                "http://i2oo.cn/Qj3zT",
                "http://i2oo.cn/SD3Go",
                "http://i2oo.cn/T6fZ9",
                "http://i2oo.cn/VBaqV",
                "http://i2oo.cn/WCafq",
                "http://i2oo.cn/Y9nQB",
                "http://i2oo.cn/ZdhgX",
                "http://i2oo.cn/bfsx1",
                "http://i2oo.cn/cbsED",
                "http://i2oo.cn/enpXZ",
                "http://i2oo.cn/CZrou",
                "http://i2oo.cn/6sraE",
                "http://i2oo.cn/5Wz4b",
                "http://i2oo.cn/jzyeA",
                "http://i2oo.cn/m7xAH",
                "http://i2oo.cn/8xxDd",
                "http://i2oo.cn/FSAVy",
                "http://i2oo.cn/qvv8K",
                "http://i2oo.cn/1QvhC",
                "http://i2oo.cn/ttuMr",
                "http://i2oo.cn/v4tdM",
                "http://i2oo.cn/Ai1u6",
                "http://i2oo.cn/yL1Us",
                "http://i2oo.cn/zFi7P",
                "http://i2oo.cn/ppJqk",
                "http://i2oo.cn/ps8qs",
                "http://i2oo.cn/pnGFK",
                "http://i2oo.cn/pakob",
                "http://i2oo.cn/p3N8t",
                "http://i2oo.cn/p958w",
                "http://i2oo.cn/pBUmS",
                "http://i2oo.cn/pUgkj",
                "http://i2oo.cn/pNwkr",
                "http://i2oo.cn/pEejH",
                "http://i2oo.cn/pH352",
                "http://i2oo.cn/pJc6i",
                "http://i2oo.cn/pLa63",
                "http://i2oo.cn/pM2gR",
                "http://i2oo.cn/pPhC6",
                "http://i2oo.cn/pQYey",
                "http://i2oo.cn/pSpeG",
                "http://i2oo.cn/pTWdY",
                "http://i2oo.cn/p7zcF",
                "http://i2oo.cn/pW7cf",
                "http://i2oo.cn/pXxbP",
                "http://i2oo.cn/pZS2C",
                "http://i2oo.cn/p2vZx",
                "http://i2oo.cn/pcQZN",
                "http://i2oo.cn/pdtYX",
                "http://i2oo.cn/pC4Xo",
                "http://i2oo.cn/pgiXn",
                "http://i2oo.cn/p5LW4",
                "http://i2oo.cn/pjFVe",
                "http://i2oo.cn/pmJ7v",
                "http://i2oo.cn/p887D",
                "http://i2oo.cn/pFGTV",
                "http://i2oo.cn/pqkSm",
                "http://i2oo.cn/p1NSh",
                "http://i2oo.cn/pt5RL",
                "http://i2oo.cn/pvUQc",
                "http://i2oo.cn/pAgPu",
                "http://i2oo.cn/pywPB",
                "http://i2oo.cn/pze4T",
                "http://i2oo.cn/sp3Mk",
                "http://i2oo.cn/sscMp",
                "http://i2oo.cn/snaLJ",
                "http://i2oo.cn/sa2Kb",
                "http://i2oo.cn/s3hJ1",
                "http://i2oo.cn/s9YJ9",
                "http://i2oo.cn/sBpHS",
                "http://i2oo.cn/sUWG5",
                "http://i2oo.cn/sDzEz",
                "http://i2oo.cn/sE7EH",
                "http://i2oo.cn/sGxNZ",
                "http://i2oo.cn/sJSDq",
                "http://i2oo.cn/sKvD3",
                "http://i2oo.cn/sMQUQ",
                "http://i2oo.cn/s4tB6",
                "http://i2oo.cn/sQ4wy",
                "http://i2oo.cn/sRiwE",
                "http://i2oo.cn/sTL9Y",
                "http://i2oo.cn/s7F3F",
                "http://i2oo.cn/sWJ3a",
                "http://i2oo.cn/sX8fP",
                "http://i2oo.cn/sZGaC",
                "http://i2oo.cn/s2knA",
                "http://i2oo.cn/scNnN",
                "http://i2oo.cn/sd5hW",
                "http://i2oo.cn/sCUs8",
                "http://i2oo.cn/sggsn",
                "http://i2oo.cn/s5wpM",
                "http://i2oo.cn/sjerd",
                "http://i2oo.cn/smfzv",
                "http://i2oo.cn/s8bzU",
                "http://i2oo.cn/sFny7",
                "http://i2oo.cn/sqZxm",
                "http://i2oo.cn/s1sxs",
                "http://i2oo.cn/stXAK",
                "http://i2oo.cn/svrvc",
                "http://i2oo.cn/sAVut",
                "http://i2oo.cn/sxyuw",
                "http://i2oo.cn/szTtT",
                "http://i2oo.cn/hrA1j",
                "http://i2oo.cn/hsR1r",
                "http://i2oo.cn/hhuiJ",
                "http://i2oo.cn/haPq2",
                "http://i2oo.cn/hf1F1",
                "http://i2oo.cn/h9MF9",
                "http://i2oo.cn/hwqoR",
                "http://i2oo.cn/hUK85",
                "http://i2oo.cn/hDomz",
                "http://i2oo.cn/hEHmG",
                "http://i2oo.cn/hGmkZ",
                "http://i2oo.cn/hJEjq",
                "http://i2oo.cn/hKjjf",
                "http://i2oo.cn/hMD5Q",
                "http://i2oo.cn/h466g",
                "http://i2oo.cn/hQBgx",
                "http://i2oo.cn/hRCgE",
                "http://i2oo.cn/hT9CX",
                "http://i2oo.cn/h7deo",
                "http://i2oo.cn/hWfea",
                "http://i2oo.cn/hXbd4",
                "http://i2oo.cn/hZnce",
                "http://i2oo.cn/h2ZbA",
                "http://i2oo.cn/hcsbD",
                "http://i2oo.cn/hdX2V",
                "http://i2oo.cn/hCrZ8",
                "http://i2oo.cn/hgVZh",
                "http://i2oo.cn/h6yYL",
                "http://i2oo.cn/hjTXd",
                "http://i2oo.cn/hkAWu",
                "http://i2oo.cn/h8RWB",
                "http://i2oo.cn/houV7",
                "http://i2oo.cn/hqP7k",
                "http://i2oo.cn/hi17s",
                "http://i2oo.cn/htMTK",
                "http://i2oo.cn/huqSb",
                "http://i2oo.cn/hAKRt",
                "http://i2oo.cn/hxoRw",
                "http://i2oo.cn/hzHQS",
                "http://i2oo.cn/nrmPj",
                "http://i2oo.cn/nsEPr",
                "http://i2oo.cn/nhj4H",
                "http://i2oo.cn/naDM2",
                "http://i2oo.cn/nf6Li",
                "http://i2oo.cn/n9BL3",
                "http://i2oo.cn/nwCKR",
                "http://i2oo.cn/nU9J6",
                "http://i2oo.cn/nDdHy",
                "http://i2oo.cn/nEfHG",
                "http://i2oo.cn/nGbGY",
                "http://i2oo.cn/nJnEF",
                "http://i2oo.cn/nKZEf",
                "http://i2oo.cn/nMsNP",
                "http://i2oo.cn/n4XDC",
                "http://i2oo.cn/nQrUx",
                "http://i2oo.cn/nRVUN",
                "http://i2oo.cn/nSyBW",
                "http://i2oo.cn/n7Two",
                "http://i2oo.cn/nVAwn",
                "http://i2oo.cn/nXR9M",
                "http://i2oo.cn/nYu3e",
                "http://i2oo.cn/n2Pfv",
                "http://i2oo.cn/nb1fD",
                "http://i2oo.cn/ndMaV",
                "http://i2oo.cn/neqnm",
                "http://i2oo.cn/ngKnh",
                "http://i2oo.cn/n6ohL",
                "http://i2oo.cn/njHsc",
                "http://i2oo.cn/nkmpu",
                "http://i2oo.cn/n8EpB",
                "http://i2oo.cn/nojrT",
                "http://i2oo.cn/nqUzk",
                "http://i2oo.cn/nigzp",
                "http://i2oo.cn/ntwyJ",
                "http://i2oo.cn/nuexb",
                "http://i2oo.cn/nA3A1",
                "http://i2oo.cn/nxcA9",
                "http://i2oo.cn/nzavS",
                "http://i2oo.cn/ar2u5",
                "http://i2oo.cn/ashtz",
                "http://i2oo.cn/ahYtH",
                "http://i2oo.cn/aap1Z",
                "http://i2oo.cn/afWiq",
                "http://i2oo.cn/a3zi3",
                "http://i2oo.cn/aw7qQ",
                "http://i2oo.cn/aBxFg",
                "http://i2oo.cn/aDSoy",
                "http://i2oo.cn/aNvoE",
                "http://i2oo.cn/aGQ8X",
                "http://i2oo.cn/aHtmF",
                "http://i2oo.cn/aK4ma",
                "http://i2oo.cn/aLikP",
                "http://i2oo.cn/a4LjC",
                "http://i2oo.cn/aPF5A",
                "http://i2oo.cn/aRJ5N",
                "http://i2oo.cn/aS86W",
                "http://i2oo.cn/a7Gg8",
                "http://i2oo.cn/aVkgn",
                "http://i2oo.cn/aXNCM",
                "http://i2oo.cn/aY5ed",
                "http://i2oo.cn/a2Udv",
                "http://i2oo.cn/abgdU",
                "http://i2oo.cn/adwc7",
                "http://i2oo.cn/aeebm",
                "http://i2oo.cn/ag3bs",
                "http://i2oo.cn/a6c2K",
                "http://i2oo.cn/ajaZc",
                "http://i2oo.cn/ak2Yt",
                "http://i2oo.cn/a8hYw",
                "http://i2oo.cn/aoYXT",
                "http://i2oo.cn/aqpWj",
                "http://i2oo.cn/aiWWr",
                "http://i2oo.cn/a1zVJ",
                "http://i2oo.cn/au772",
                "http://i2oo.cn/avxTi",
                "http://i2oo.cn/axST9",
                "http://i2oo.cn/ayvSR",
                "http://i2oo.cn/frQR6",
                "http://i2oo.cn/fptQz",
                "http://i2oo.cn/fh4QG",
                "http://i2oo.cn/fniPZ",
                "http://i2oo.cn/ffL4q",
                "http://i2oo.cn/f3F4f",
                "http://i2oo.cn/fwJMQ",
                "http://i2oo.cn/fB8Lg",
                "http://i2oo.cn/fDGKx",
                "http://i2oo.cn/fNkKE",
                "http://i2oo.cn/fGNJX",
                "http://i2oo.cn/fH5Ho",
                "http://i2oo.cn/fKUHa",
                "http://i2oo.cn/fLgG4",
                "http://i2oo.cn/f4wEe",
                "http://i2oo.cn/fPeNA",
                "http://i2oo.cn/fR3ND",
                "http://i2oo.cn/fScDV",
                "http://i2oo.cn/f7aU8",
                "http://i2oo.cn/fV2Uh",
                "http://i2oo.cn/fXhBL",
                "http://i2oo.cn/rCx1 ",
                "http://i2oo.cn/pVCED",
                "http://i2oo.cn/syeXZ",
                "http://i2oo.cn/nTdou",
                "http://i2oo.cn/aAdaE",
                "http://i2oo.cn/3Rc4b",
                "http://i2oo.cn/9ubeA",
                "http://i2oo.cn/BP2AH",
                "http://i2oo.cn/U12Dd",
                "http://i2oo.cn/NMZVy",
                "http://i2oo.cn/EqY8K",
                "http://i2oo.cn/HKYhC",
                "http://i2oo.cn/JoXMr",
                "http://i2oo.cn/LHWdM",
                "http://i2oo.cn/MmVu6",
                "http://i2oo.cn/PEVUs",
                "http://i2oo.cn/Qj77P",
                "http://i2oo.cn/SDTkj",
                "http://i2oo.cn/T6Tsn",
                "http://i2oo.cn/VBSKR",
                "http://i2oo.cn/WCRbm",
                "http://i2oo.cn/Y9Qtf",
                "http://i2oo.cn/ZdQwT",
                "http://i2oo.cn/bfPSo",
                "http://i2oo.cn/cb4j9",
                "http://i2oo.cn/en4rV",
                "http://i2oo.cn/CZMHq",
                "http://i2oo.cn/6sL2B",
                "http://i2oo.cn/5XKiX",
                "http://i2oo.cn/krK31",
                "http://i2oo.cn/mVJRD",
                "http://i2oo.cn/8yH6Z",
                "http://i2oo.cn/FTGyu",
                "http://i2oo.cn/qAGGE",
                "http://i2oo.cn/1REYb",
                "http://i2oo.cn/tuNFA",
                "http://i2oo.cn/vPNfH",
                "http://i2oo.cn/A1DPd",
                "http://i2oo.cn/yMUCy",
                "http://i2oo.cn/zqBxK",
                "http://i2oo.cn/ppKBN",
                "http://i2oo.cn/psowX",
                "http://i2oo.cn/pnH9o",
                "http://i2oo.cn/pam9n",
                "http://i2oo.cn/p3E34",
                "http://i2oo.cn/p9jfe",
                "http://i2oo.cn/pBDav",
                "http://i2oo.cn/pU6aD",
                "http://i2oo.cn/pNBnV",
                "http://i2oo.cn/pEChm",
                "http://i2oo.cn/pH9hh",
                "http://i2oo.cn/pJdsL",
                "http://i2oo.cn/pLfpc",
                "http://i2oo.cn/pMbru",
                "http://i2oo.cn/pPnrB",
                "http://i2oo.cn/pQYzT",
                "http://i2oo.cn/pSpyk",
                "http://i2oo.cn/pTWyp",
                "http://i2oo.cn/p7zxJ",
                "http://i2oo.cn/pW7Ab",
                "http://i2oo.cn/pXxv1",
                "http://i2oo.cn/pZSv9",
                "http://i2oo.cn/p2vuS",
                "http://i2oo.cn/pcQt5",
                "http://i2oo.cn/pdt1z",
                "http://i2oo.cn/pC41H",
                "http://i2oo.cn/pgiiZ",
                "http://i2oo.cn/p5Lqq",
                "http://i2oo.cn/pjFq3",
                "http://i2oo.cn/pmJFQ",
                "http://i2oo.cn/p88o6",
                "http://i2oo.cn/pFG8y",
                "http://i2oo.cn/pqk8E",
                "http://i2oo.cn/p1NmY",
                "http://i2oo.cn/pt5kF",
                "http://i2oo.cn/pvUka",
                "http://i2oo.cn/pAgjP",
                "http://i2oo.cn/pyw5C",
                "http://i2oo.cn/pze6A",
                "http://i2oo.cn/sp36N",
                "http://i2oo.cn/sscgW",
                "http://i2oo.cn/snaC8",
                "http://i2oo.cn/sa2Cn",
                "http://i2oo.cn/s3heM",
                "http://i2oo.cn/s9Ydd",
                "http://i2oo.cn/sBpcv",
                "http://i2oo.cn/sUWcU",
                "http://i2oo.cn/sDzb7",
                "http://i2oo.cn/sE72m",
                "http://i2oo.cn/sGx2s",
                "http://i2oo.cn/sJSZK",
                "http://i2oo.cn/sKvYc",
                "http://i2oo.cn/sMQXt",
                "http://i2oo.cn/s4tXw",
                "http://i2oo.cn/sQ4WT",
                "http://i2oo.cn/sRiVj",
                "http://i2oo.cn/sTLVr",
                "http://i2oo.cn/s7F7J",
                "http://i2oo.cn/sWJT2",
                "http://i2oo.cn/sX8S1",
                "http://i2oo.cn/sZGS9",
                "http://i2oo.cn/s2kRR",
                "http://i2oo.cn/scNQ5",
                "http://i2oo.cn/sd5Pz",
                "http://i2oo.cn/sCUPG",
                "http://i2oo.cn/sgg4Z",
                "http://i2oo.cn/s5wMq",
                "http://i2oo.cn/sjeMf",
                "http://i2oo.cn/sm3LQ",
                "http://i2oo.cn/s8cKg",
                "http://i2oo.cn/sFaJx",
                "http://i2oo.cn/sq2JE",
                "http://i2oo.cn/s1hHX",
                "http://i2oo.cn/stYGo",
                "http://i2oo.cn/svpGa",
                "http://i2oo.cn/sAWE4",
                "http://i2oo.cn/sxzNe",
                "http://i2oo.cn/sz7DA",
                "http://i2oo.cn/hrxDD",
                "http://i2oo.cn/hsSUV",
                "http://i2oo.cn/hhvB8",
                "http://i2oo.cn/haQBh",
                "http://i2oo.cn/hftwL",
                "http://i2oo.cn/h949d",
                "http://i2oo.cn/hwi3u",
                "http://i2oo.cn/hUL3B",
                "http://i2oo.cn/hDFf7",
                "http://i2oo.cn/hEJak",
                "http://i2oo.cn/hG8as",
                "http://i2oo.cn/hJGnK",
                "http://i2oo.cn/hKkhb",
                "http://i2oo.cn/hMNst",
                "http://i2oo.cn/h45sw",
                "http://i2oo.cn/hQUpS",
                "http://i2oo.cn/hRgrj",
                "http://i2oo.cn/hTwrr",
                "http://i2oo.cn/h7dzH",
                "http://i2oo.cn/hWfy2",
                "http://i2oo.cn/hXbxi",
                "http://i2oo.cn/hZnx3",
                "http://i2oo.cn/h2ZAR",
                "http://i2oo.cn/hcsv6",
                "http://i2oo.cn/hdXuy",
                "http://i2oo.cn/hCruG",
                "http://i2oo.cn/hgVtY",
                "http://i2oo.cn/h6y1F",
                "http://i2oo.cn/hjT1f",
                "http://i2oo.cn/hkAiP",
                "http://i2oo.cn/h8RqC",
                "http://i2oo.cn/houFx",
                "http://i2oo.cn/hqPFN",
                "http://i2oo.cn/hi1oW",
                "http://i2oo.cn/htM8o",
                "http://i2oo.cn/huq8n",
                "http://i2oo.cn/hAKmM",
                "http://i2oo.cn/hxoke",
                "http://i2oo.cn/hzHjv",
                "http://i2oo.cn/nrmjD",
                "http://i2oo.cn/nsE5V",
                "http://i2oo.cn/nhj6m",
                "http://i2oo.cn/naD6h",
                "http://i2oo.cn/nf6gL",
                "http://i2oo.cn/n9BCc",
                "http://i2oo.cn/nwCeu",
                "http://i2oo.cn/nU9eB",
                "http://i2oo.cn/nDddT",
                "http://i2oo.cn/nEfck",
                "http://i2oo.cn/nGbcp",
                "http://i2oo.cn/nJnbJ",
                "http://i2oo.cn/nKZ2b",
                "http://i2oo.cn/nMsZ1",
                "http://i2oo.cn/n4XZ9",
                "http://i2oo.cn/nQrYS",
                "http://i2oo.cn/nRVX5",
                "http://i2oo.cn/nSyWz",
                "http://i2oo.cn/n7TWH",
                "http://i2oo.cn/nVAVZ",
                "http://i2oo.cn/nXR7q",
                "http://i2oo.cn/nYu73",
                "http://i2oo.cn/n2PTQ",
                "http://i2oo.cn/nb1Sg",
                "http://i2oo.cn/ndMRy",
                "http://i2oo.cn/neqRE",
                "http://i2oo.cn/ngKQX",
                "http://i2oo.cn/n6oPF",
                "http://i2oo.cn/njHPa",
                "http://i2oo.cn/nkm4P",
                "http://i2oo.cn/n8EMC",
                "http://i2oo.cn/nojLA",
                "http://i2oo.cn/nqDLN",
                "http://i2oo.cn/ni6KW",
                "http://i2oo.cn/ntBJ8",
                "http://i2oo.cn/nuCJn",
                "http://i2oo.cn/nA9HM",
                "http://i2oo.cn/nxdGd",
                "http://i2oo.cn/nzfEv",
                "http://i2oo.cn/arbEU",
                "http://i2oo.cn/asnN7",
                "http://i2oo.cn/ahZDm",
                "http://i2oo.cn/aasDs",
                "http://i2oo.cn/afXUK",
                "http://i2oo.cn/a9rBc",
                "http://i2oo.cn/awVwt",
                "http://i2oo.cn/aByww",
                "http://i2oo.cn/aDT9T",
                "http://i2oo.cn/aNA3j",
                "http://i2oo.cn/aGR3r",
                "http://i2oo.cn/aHufJ",
                "http://i2oo.cn/aKPa2",
                "http://i2oo.cn/aL1ni",
                "http://i2oo.cn/a4Mn9",
                "http://i2oo.cn/aPqhR",
                "http://i2oo.cn/aRKs6",
                "http://i2oo.cn/aSopz",
                "http://i2oo.cn/a7HpG",
                "http://i2oo.cn/aVmrZ",
                "http://i2oo.cn/aXNzq",
                "http://i2oo.cn/aY5zf",
                "http://i2oo.cn/a2UyQ",
                "http://i2oo.cn/abgxg",
                "http://i2oo.cn/adwAx",
                "http://i2oo.cn/aeeAE",
                "http://i2oo.cn/ag3vX",
                "http://i2oo.cn/a6cuo",
                "http://i2oo.cn/ajaua",
                "http://i2oo.cn/ak2t4",
                "http://i2oo.cn/a8h1e",
                "http://i2oo.cn/aoYiA",
                "http://i2oo.cn/aqpiD",
                "http://i2oo.cn/aiWqV",
                "http://i2oo.cn/a1zF8",
                "http://i2oo.cn/au7Fh",
                "http://i2oo.cn/avxoL",
                "http://i2oo.cn/axS8d",
                "http://i2oo.cn/ayvmu",
                "http://i2oo.cn/frQmB",
                "http://i2oo.cn/fptk7",
                "http://i2oo.cn/fh4jk",
                "http://i2oo.cn/fnijp",
                "http://i2oo.cn/ffL5K",
                "http://i2oo.cn/f3F6b",
                "http://i2oo.cn/fwJg1",
                "http://i2oo.cn/fB8gw",
                "http://i2oo.cn/fDGCS",
                "http://i2oo.cn/fNkej",
                "http://i2oo.cn/fGNer",
                "http://i2oo.cn/fH5dH",
                "http://i2oo.cn/fKUc2",
                "http://i2oo.cn/fLgbi",
                "http://i2oo.cn/f4wb3",
                "http://i2oo.cn/fPe2R",
                "http://i2oo.cn/fR3Z6",
                "http://i2oo.cn/fScYy",
                "http://i2oo.cn/f7aYG",
                "http://i2oo.cn/fV2XY",
                "http://i2oo.cn/fXhWF",
                "http://i2oo.cn/rprSo",
                "http://i2oo.cn/pVzj9",
                "http://i2oo.cn/syzrV",
                "http://i2oo.cn/nTyHq",
                "http://i2oo.cn/aAx2B",
                "http://i2oo.cn/3RAiX",
                "http://i2oo.cn/9uA31",
                "http://i2oo.cn/BPvRD",
                "http://i2oo.cn/U1u6Z",
                "http://i2oo.cn/NMtyu",
                "http://i2oo.cn/EqtGE",
                "http://i2oo.cn/HK1Yb",
                "http://i2oo.cn/JoiFA",
                "http://i2oo.cn/LHifH",
                "http://i2oo.cn/MmqPd",
                "http://i2oo.cn/PEFCy",
                "http://i2oo.cn/QjoxK",
                "http://i2oo.cn/SDoNC",
                "http://i2oo.cn/T68Xr",
                "http://i2oo.cn/VBmoM",
                "http://i2oo.cn/WCmn6",
                "http://i2oo.cn/Y9k4s",
                "http://i2oo.cn/ZdjeP",
                "http://i2oo.cn/bf5vj",
                "http://i2oo.cn/cb5Dn",
                "http://i2oo.cn/en6VR",
                "http://i2oo.cn/CZgmm",
                "http://i2oo.cn/6sghf",
                "http://i2oo.cn/5XCLT",
                "http://i2oo.cn/kreco",
                "http://i2oo.cn/mVdu9",
                "http://i2oo.cn/8ydBV",
                "http://i2oo.cn/FTcTq",
                "http://i2oo.cn/qAbkB",
                "http://i2oo.cn/1RbpX",
                "http://i2oo.cn/tu2J1",
                "http://i2oo.cn/vPZbD",
                "http://i2oo.cn/A1Y1Z",
                "http://i2oo.cn/yMY9u",
                "http://i2oo.cn/zqXSE",
                "http://i2oo.cn/ppKW5",
                "http://i2oo.cn/psoVz",
                "http://i2oo.cn/pnHVH",
                "http://i2oo.cn/pam7Z",
                "http://i2oo.cn/p3ETq",
                "http://i2oo.cn/p9jT3",
                "http://i2oo.cn/pBDSQ",
                "http://i2oo.cn/pU6R6",
                "http://i2oo.cn/pNBQy",
                "http://i2oo.cn/pECQE",
                "http://i2oo.cn/pH9PY",
                "http://i2oo.cn/pJd4F",
                "http://i2oo.cn/pLf4a",
                "http://i2oo.cn/pMbMP",
                "http://i2oo.cn/pPnLC",
                "http://i2oo.cn/pQZKA",
                "http://i2oo.cn/pSsKN",
                "http://i2oo.cn/pTXJW",
                "http://i2oo.cn/pVrH8",
                "http://i2oo.cn/pWVHn",
                "http://i2oo.cn/pXyGM",
                "http://i2oo.cn/pZTEd",
                "http://i2oo.cn/p2ANv",
                "http://i2oo.cn/pcRNU",
                "http://i2oo.cn/pduD7",
                "http://i2oo.cn/pCPUm",
                "http://i2oo.cn/pg1Us",
                "http://i2oo.cn/p5MBK",
                "http://i2oo.cn/pjqwc",
                "http://i2oo.cn/pmK9t",
                "http://i2oo.cn/p8o9w",
                "http://i2oo.cn/pFH3T",
                "http://i2oo.cn/pqmfj",
                "http://i2oo.cn/p1Efr",
                "http://i2oo.cn/ptjaJ",
                "http://i2oo.cn/pvDn2",
                "http://i2oo.cn/pA6h1",
                "http://i2oo.cn/pyBh9",
                "http://i2oo.cn/pzCsR",
                "http://i2oo.cn/sp9p5",
                "http://i2oo.cn/ssdrz",
                "http://i2oo.cn/snfrG",
                "http://i2oo.cn/sa2zZ",
                "http://i2oo.cn/s3hyq",
                "http://i2oo.cn/s9Yyf",
                "http://i2oo.cn/sBpxQ",
                "http://i2oo.cn/sUWAg",
                "http://i2oo.cn/sDzvx",
                "http://i2oo.cn/sE7vE",
                "http://i2oo.cn/sGxuX",
                "http://i2oo.cn/sJSto",
                "http://i2oo.cn/sKvta",
                "http://i2oo.cn/sMQ14",
                "http://i2oo.cn/s4tie",
                "http://i2oo.cn/sQ4qA",
                "http://i2oo.cn/sRiqD",
                "http://i2oo.cn/sTLFV",
                "http://i2oo.cn/s7Fo8",
                "http://i2oo.cn/sWJoh",
                "http://i2oo.cn/sX88L",
                "http://i2oo.cn/sZGmd",
                "http://i2oo.cn/s2kku",
                "http://i2oo.cn/scNkB",
                "http://i2oo.cn/sd5j7",
                "http://i2oo.cn/sCU5k",
                "http://i2oo.cn/sgg5s",
                "http://i2oo.cn/s5w6K",
                "http://i2oo.cn/sjegb",
                "http://i2oo.cn/sm3Ct",
                "http://i2oo.cn/s8cCw",
                "http://i2oo.cn/sFaeS",
                "http://i2oo.cn/sq2dj",
                "http://i2oo.cn/s1hdr",
                "http://i2oo.cn/stYcH",
                "http://i2oo.cn/svpb2",
                "http://i2oo.cn/sAW2i",
                "http://i2oo.cn/sxz23",
                "http://i2oo.cn/sz7ZR",
                "http://i2oo.cn/hrxY6",
                "http://i2oo.cn/hsSXy",
                "http://i2oo.cn/hhvXG",
                "http://i2oo.cn/haQWY",
                "http://i2oo.cn/hftVF",
                "http://i2oo.cn/h94Vf",
                "http://i2oo.cn/hwi7P",
                "http://i2oo.cn/hULTC",
                "http://i2oo.cn/hDFSx",
                "http://i2oo.cn/hEJSN",
                "http://i2oo.cn/hG8RW",
                "http://i2oo.cn/hJGQo",
                "http://i2oo.cn/hKkQn",
                "http://i2oo.cn/hMNPM",
                "http://i2oo.cn/h454e",
                "http://i2oo.cn/hQUMv",
                "http://i2oo.cn/hRgMD",
                "http://i2oo.cn/hTwLV",
                "http://i2oo.cn/h7eKm",
                "http://i2oo.cn/hW3Kh",
                "http://i2oo.cn/hXcJL",
                "http://i2oo.cn/hZaHc",
                "http://i2oo.cn/h22Gu",
                "http://i2oo.cn/hchGB",
                "http://i2oo.cn/hdYET",
                "http://i2oo.cn/hCpNk",
                "http://i2oo.cn/hgWNp",
                "http://i2oo.cn/h6zDJ",
                "http://i2oo.cn/hj7Ub",
                "http://i2oo.cn/hkxB1",
                "http://i2oo.cn/h8SB9",
                "http://i2oo.cn/hovwS",
                "http://i2oo.cn/hqQ95",
                "http://i2oo.cn/hit3z",
                "http://i2oo.cn/ht43H",
                "http://i2oo.cn/huifZ",
                "http://i2oo.cn/hALaq",
                "http://i2oo.cn/hxFa3",
                "http://i2oo.cn/hzJnQ",
                "http://i2oo.cn/nr8hg",
                "http://i2oo.cn/nsGsy",
                "http://i2oo.cn/nhksE",
                "http://i2oo.cn/naNpX",
                "http://i2oo.cn/nf5rF",
                "http://i2oo.cn/n9Ura",
                "http://i2oo.cn/nwCzP",
                "http://i2oo.cn/nU9yC",
                "http://i2oo.cn/nDdxA",
                "http://i2oo.cn/nEfxN",
                "http://i2oo.cn/nGbAW",
                "http://i2oo.cn/nJnv8",
                "http://i2oo.cn/nKZvn",
                "http://i2oo.cn/nMsuM",
                "http://i2oo.cn/n4Xtd",
                "http://i2oo.cn/nQr1v",
                "http://i2oo.cn/nRV1U",
                "http://i2oo.cn/nSyi7",
                "http://i2oo.cn/n7Tqm",
                "http://i2oo.cn/nVAqs",
                "http://i2oo.cn/nXRFK",
                "http://i2oo.cn/nYuoc",
                "http://i2oo.cn/n2P8t",
                "http://i2oo.cn/nb18w",
                "http://i2oo.cn/ndMmT",
                "http://i2oo.cn/neqkj",
                "http://i2oo.cn/ngKkr",
                "http://i2oo.cn/n6ojJ",
                "http://i2oo.cn/njH52",
                "http://i2oo.cn/nkm6i",
                "http://i2oo.cn/n8E69",
                "http://i2oo.cn/nojgR",
                "http://i2oo.cn/nqDC6",
                "http://i2oo.cn/ni6ez",
                "http://i2oo.cn/ntBeG",
                "http://i2oo.cn/nuCdZ",
                "http://i2oo.cn/nA9cq",
                "http://i2oo.cn/nxdcf",
                "http://i2oo.cn/nzfbQ",
                "http://i2oo.cn/arb2g",
                "http://i2oo.cn/asnZx",
                "http://i2oo.cn/ahZZE",
                "http://i2oo.cn/aasYX",
                "http://i2oo.cn/afXXo",
                "http://i2oo.cn/a9rXa",
                "http://i2oo.cn/awVW4",
                "http://i2oo.cn/aByVe",
                "http://i2oo.cn/aDT7A",
                "http://i2oo.cn/aNA7D",
                "http://i2oo.cn/aGRTV",
                "http://i2oo.cn/aHuS8",
                "http://i2oo.cn/aKPSh",
                "http://i2oo.cn/aL1RL",
                "http://i2oo.cn/a4MQd",
                "http://i2oo.cn/aPqPu",
                "http://i2oo.cn/aRKPB",
                "http://i2oo.cn/aSo47",
                "http://i2oo.cn/a7HMk",
                "http://i2oo.cn/aVmMp",
                "http://i2oo.cn/aXELK",
                "http://i2oo.cn/aYjKb",
                "http://i2oo.cn/a2DJ1",
                "http://i2oo.cn/ab6Jw",
                "http://i2oo.cn/adBHS",
                "http://i2oo.cn/aeCGj",
                "http://i2oo.cn/ag9Gr",
                "http://i2oo.cn/a6dEH",
                "http://i2oo.cn/ajfN2",
                "http://i2oo.cn/akbDi",
                "http://i2oo.cn/a8nD3",
                "http://i2oo.cn/aoZUR",
                "http://i2oo.cn/aqsB6",
                "http://i2oo.cn/aiXwy",
                "http://i2oo.cn/atrwG",
                "http://i2oo.cn/auV9Y"
            };
        }
    }
}